FROM public.ecr.aws/sagemaker/sagemaker-distribution:3.4.3-cpu

USER root
RUN apt-get update && apt-get install -y git curl

USER sagemaker-user
WORKDIR /opt/ml/code

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY inference.py .
COPY serve.py .

ENTRYPOINT ["python", "serve.py"]
