project:
  name: chronos-forecasting

paths:
  base_model: s3://chronos-presmanes/models/base/chronos-bolt-tiny.tar.gz
  training_data: s3://chronos-presmanes/data/Turbine_Data.csv
  production_model: s3://chronos-presmanes/models/fine-tunned/chronos-bolt-tiny-tuned.tar.gz

  dataset_base: s3://chronos-deployment/data/

s3:
  bucket: chronos-presmanes
  upload:
    models:
      local_dir: ./models
      s3_prefix: models/base/
    data:
      s3_prefix: data/
  production_models:
    s3_prefix: models/

dataset:
  base_file: ./data/wind-power-forecasting/Turbine_Data.csv
  processed_file: ./data/wind-power-forecasting/processed/Turbine_data_processed.parquet
  pipeline_file: ./data/wind-power-forecasting/pipeline_file.joblib
  metadata_file: ./data/wind-power-forecasting/metadata.json

ecr:
  training:
    repo_name: chronos-training
    image_uri: 619071308424.dkr.ecr.eu-west-1.amazonaws.com/chronos-training:latest
  deployment:
    repo_name: chronos-deployment

sagemaker:
  training:
    limit_time: 300  # ✅ 5 minutes for testing (use 3600 for full fine-tuning)
    instance_type: ml.g4dn.xlarge  # ✅ GPU instance (NVIDIA T4, 16GB) for fine-tuning
    instance_count: 1
  inference:
    instance_type: ml.t2.medium  # ✅ CPU instance for inference (cost-effective)
    instance_count: 1
  endpoint_name: chronos-endpoint-prod-6
