FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.2.0-cpu-py310-ubuntu20.04-sagemaker

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE

RUN apt-get update && apt-get install -y git curl && pip install --upgrade pip

WORKDIR /opt/ml/code
COPY . .

RUN pip install -r requirements.txt

ENV PYTHONPATH="/opt/ml/code:${PYTHONPATH}"